export const info = {
    big_data: [
        {
            title: "About NASA and big data",
            text: "Big data is closely related to large amounts of data that cannot be processed or analyzed using traditional methods. NASA is using this type of technology to ensure the reliability of thousands of sensors monitoring the Earth's atmosphere and outer space, and over 100 current missions in operation, generating about 12 TB of raw data per day, which are then sent back to Earth."
        },
        {
            title: "How big data is used?",
            text: " - The Quantum Artificial Intelligence Laboratory (QuAIL).\n- The agencies of Supercomputers that perform simulation and modeling.\n- Storage of wholesale amounts of data on Earth Science and Distributed Active Archive Centers (DAACs).\n- Cyber Security of its networks and the NACRA- the Network Activity Cybersecurity Risk Assessment."
        },
        {
            title: "Processing and managing big data",
            text: "NASA manages and processes big data through MPCS (Mission Data Processing and Management System). “The Curiosity Rover recently used this system on a mission to Mars. During the expedition” (Shannon, 2019). MPCS used data from NASA's Mars Reconnaissance Orbiter as well as deep space systems to guide the Curiosity rover during its mission in real-time. In the past, this process took hours or even days. In addition, NASA is also using big data in navigation. NASA's Mission Control Team is using big data to create custom visualizations of data generated by MPCS to guide NASA teams on missions."
        },
        {
            title: "NASA’s technologies for big data",
            text: "Talking about technologies, ”NASA’s Pleiades, one of the world's most powerful supercomputers, represents NASA's state-of-the-art technology for meeting the agency's supercomputing requirements, enabling NASA scientists and engineers to conduct modeling and simulation for NASA projects.” (Pleiades Supercomputer, n.d.). This supercomputer was recently used to evaluate large amounts of star data collected by NASA's Kepler spacecraft. Thanks to this analysis, NASA was able to detect Earth-sized planets in the Milky Way galaxy for searching the suitable exoplanets."
        },
        {
            title: "Role at climate change",
            text: "Despite being a leading expert in the climate change problem, NASA’s role is not to formulate climate policies or prescribe specific responses or solutions to climate change. “Its purview does include providing the robust scientific data needed to understand climate change and evaluating the impact of efforts to address it” (NASA Global Climate Change, n.d.). NASA research is critical to helping scientists study the causes of climate change, which directly affects the way our heritage lives. The large amount of data received from satellites is processed and further used by NASA to determine the possible trajectories of clouds, probability of rains as well as the track of overall temperature on the planet."
        }
    ],
    nisar: [
        {
            title: "NASA partnership with the Indian Space Research Organization (ISRO)",
            text: "NISAR is a joint Earth-observing mission between NASA and the Indian Space Research Organization (ISRO). NASA and ISRO are providing two radars that are optimized each in their own way to allow the mission to observe a wider range of changes than either one alone."
        },
        {
            title: "How it works?",
            text: "NISAR will be the first radar of its kind in space to systematically map Earth, using two different radar frequencies (L-band and S-band) to measure changes in our planet's surface less than a centimeter across. Synthetic aperture radar (SAR) refers to a technique for producing fine-resolution images from a resolution-limited radar system."
        },
        {
            title: "About data",
            text: "NISAR will add a tremendous new data set to create new and greatly improve upon existing applications. By virtue of the planned frequent and regular sampling of some of the world's most hazard-prone areas, these data will be a rich source of information to guide development of applications and their associated scientific studies. They will be a reliable data source over the life of the mission for proactive planning for disasters, and will have a store of pre-disaster images available to rapidly understand what transpired in the disaster, leading to the development of actionable applications that could inform the government for consideration of future operational missions.\nWater resource monitoring, infrastructure monitoring, and other value-added applications will also be revolutionized by access to these data. To learn more about applications, there is more information in the Applications White Papers."
        },
        {
            title: "Problem",
            text: "For more than 100 years, scientists have considered diminishing glaciers and sea ice to be an early indicator of global warming. Ice sheets and glaciers are already melting fast enough to be the largest contributors to sea level rise, with a potential to raise sea levels substantially in the coming century. Satellite observations collected over the past three decades show that summer sea ice cover is decreasing drastically and may vanish entirely within decades. This loss will have a profound effect on life, climate and commercial activities in the Arctic, while the loss of land ice will impact an important source of water for millions of people. Collectively, these effects mean that ice loss — even in remote regions — has global economic and health implications as climate changes."
        },
        {
            title: "Solution",
            text: "NISAR will provide key data necessary to make informed environmental and economic decisions. NISAR will provide the most complete measurements of rapidly changing sea ice in both polar regions. Understanding the causes and mechanisms of ice loss requires knowledge of ice thickness, sea ice types and sea ice dynamics. Melting permafrost releases methane to the atmosphere, erodes soil and impacts surface water distribution and the stability of infrastructure. NISAR will measure heave and thaw in the near-surface active layer of permafrost."
        }
    ],
    maia: [
        {
            title: "What is MAIA ?",
            text: "MAIA uses a twin-camera instrument that will make radiometric and polarimetric measurements needed to characterize the sizes, compositions, and quantities of particulate matter in air pollution. Multi-Angle Imager for Aerosols, an investigation that will seek to understand how different types of air pollution affect human health."
        },
        {
            title: "MAIA and your health",
            text: "How risky is air contamination? The Global Burden of Disease is a pivotal investigation of what causes infection around the world. It tracks down that breathing particulate matter air pollution is the biggest ecological danger factor for sudden passing. In 2019, outside air contamination caused 4.1 million unexpected losses, generally in quickly agricultural nations. Improving air quality can lengthen millions of lives.However, PM (particulate matter) is complex: it’s made up of particles of different sizes, shapes, and chemical compositions. Furthermore, the amounts vary widely from place to place and from season to season. Scientists have shown that PM increases the risks of illness and premature death. Yet the relative danger of these different PM types is less well understood. Numerous logical examinations have shown that breathing air contamination, explicitly airborne particulate matter (PM), builds your danger of a few medical issues. This is because bigger particles can aggravate the lungs and more modest particles can cause irritation that influences different organs. Researchers have tracked down that breathing PM causes coronary illness, cardiovascular failures, and strokes. Other logical investigations show that individuals who inhale more PM are bound to foster cellular breakdown in the lungs, lower respiratory contaminations, ongoing obstructive aspiratory illness (COPD), and various issues during pregnancy and birth"
        },
        {
            title: "The MAIA Investigation",
            text: "Why MAIA investigation is so useful? That is because MAIA collects a lot of data. This data has a big range of use, and one of those examples are: The MAIA investigation is how we will provide a highly detailed view of key types of particulate matter air pollution (PM). The MAIA satellite instrument will view a set of Primary TArget Areas from space. This data will be combined with other information, including measurements from air pollution monitors on the ground and outputs from computer models. The results will be used to create daily maps of PM amounts in the Primary Target Areas. These maps and health records will be used by epidemiologists to conduct health studies. The findings from these studies will provide information about which types of PM are most harmful."
        }
    ]
}

export const gpm = [
    {
        title: "Global Precipitation Measurement (GPM) NASA mission, Precipitation data and its usage for prediction and mitigation of Natural Disasters.",
        text: "Precipitation analysis and Flooding prediction is one of the main objectives of modern society. Annually, people around the world suffer from unpredicted water movement and flooding occurring spontaneously and affecting multiple spheres of human life. It’s very important for making this world a safer place for each person on our planet. Specialists and scientists from National Aeronautics and Space Administration (NASA) investigate and observe such topics collecting information from the satellites and working on its utility. In this chapter we will review methodology and technologies used for precipitation data collection, identify what affects its value for certain field - flood prediction and mitigation. "
    },
    {
        title: "What is GPM?",
        text: "Global Precipitation Measurement satellite – technology used for precipitation data collection. It is a joint international mission of Japan and the USA, which consists in collecting and analyzing information about disasters such as floods and landslides to prevent their occurrence, as well as in detecting abrupt changes in precipitation to determine climate change. It is also very important to note that the data sets obtained help in the formation of a common database, combined by algorithms and accumulating information to identify patterns and changes in precipitation over a certain period of time. The GPM mission has several scientific goals, including 1) improving precipitation measurements from space; 2) improving knowledge about precipitation systems, water cycle variability, and freshwater availability; 3) improving climate modeling and forecasting capabilities; 4) improving weather forecasting and four-dimensional (4D) reanalysis; and 5) improving hydrological modeling and forecasting. (Skofronick-Jackson et al., 2017)."
    },
    {
        title: "Data collection",
        text: "The GPM Core Observatory satellite is equipped with two auxiliary instruments - GMI (GPM Microwave Imager) and dual-frequency precipitation Radar (DPR). They measure the properties of precipitation from orbit using a method of combining passive and active remote sensing. These measurements give us understanding of the behavior and properties of precipitation and serve as a source for adjusting, integrating and improving precipitation measurements with help of additional research and operational microwave sensing satellites to create a global database of precipitation measurements. "
    }
]